---

- hosts: all
  tasks:
    - name: site | hello world
      shell: echo "Hi! Ansible is working"
    - name: Execute the script
      command: hostname
      register: out
    - debug: var=out.stdout_lines
