---

- name: Transfer and execute a script.
  hosts: all
  user: root
  sudo: no
  tasks:
     - name: Transfer the script
       copy: src=test.sh dest=/usr/src/test.sh mode=0777

     - name: Execute the script
       local_action: command sh usr/src/test.sh
