---

- name: Transfer and execute a script.
  hosts: all
  user: root
  sudo: no
  tasks:
     - name: Transfer the script
       copy: src=test.php dest=/usr/src/test.php mode=0777

     - name: Execute the script
       local_action: command /usr/bin/php /usr/src/test.php
